spring:
  application:
    name: authservice
  datasource:
    url: ${DB_URL:jdbc:mysql://localhost:3306/erevmax}
    username: ${DB_USERNAME:root}
    password: ${DB_PASSWORD:root}
  jpa:
    hibernate:
      ddl-auto: update
      dialect: org.hibernate.dialect.MySQLDialect
    show-sql: true
  security:
    user:
      name: user
      password: 123
server:
  port: 8080
#security:
  #jwt:
    #secret: ${JWT_SECRET}
    #issuer: ${JWT_ISSUER}
    #access-ttl-seconds: ${JWT_ACCESS_TTL_SECONDS}
    #refresh-ttl-seconds: ${JWT_REFRESH_TTL_SECONDS}
    #refresh-token-cookie-name: ${JWT_REFRESH_TOKEN_COOKIE_NAME}
    #cookie-secure: ${JWT_COOKIE_SECURE}
    #cookie-http-only: ${JWT_COOKIE_HTTP_ONLY}
    #cookie-same-site: ${JWT_COOKIE_SAME_SITE}
    #cookie-domain: ${JWT_COOKIE_DOMAIN}
